### ISSUE TITLE
Not an Issue, thanks!

### ISSUE THREAD

**Issue by 7sharp9** [ericx20/zz-method-docs#33]
Hi, Im learning cubing and found this quite useful.  Ive been reading the http://cube.rider.biz articles too from wayback machine but your site has got me suceeding with a full solve following the instructions. 

The EO part is the most time consuming.  I suppose the intuative F2L is also but its a slow bite by bite prgress whereas the EO seems to leave me staring at the cube trying to remember which edges are bad!

Anyway, just wanted to say thanks for putting this together!

**Comment by ericx20** [comment]
Hey Dave, thanks for your kind words!
Welcome to the cubing hobby and congrats on your first ZZ solve.
I'm glad I could help, seeing this resource being used means a lot to me.
Best of luck on your progress, keep it up!
